[package]
edition = "2021"
name = "mc-networking"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mc-networking-macros = {path = "../mc-networking-macros"}
